// /// <reference types="./types/global" />
// /// <reference path="./dist/styled-jsx/types/global.d.ts" />
/// <reference path="./Footer/index.d.ts" />
/// <reference path="./Image/index.d.ts" />
/// <reference path="./Image/index.d.ts" />
/// <reference path="./Input/index.d.ts" />
/// <reference path="./TextArea/index.d.ts" />
/// <reference path="./Link/index.d.ts" />
/// <reference path="./Navbar/index.d.ts" />
/// <reference path="./SiteWrapper/index.d.ts" />
/// <reference path="./Heading/index.d.ts" />
